//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public System.Guid atte_id { get; set; }
        public Nullable<int> atte_proj_id { get; set; }
        public Nullable<System.DateTime> atte_timein { get; set; }
        public Nullable<System.DateTime> atte_timeout { get; set; }
    
        public virtual NewManpower NewManpower { get; set; }
    }
}
