//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Credential
    {
        public int emp_no { get; set; }
        public string username { get; set; }
        public string password { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
