//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Limits
    {
        public string in_code { get; set; }
        public int maximum { get; set; }
        public int minimum { get; set; }
        public int reorder { get; set; }
        public Nullable<int> running { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
