//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string in_code { get; set; }
        public string in_name { get; set; }
        public string in_category { get; set; }
        public string in_type { get; set; }
        public string in_size { get; set; }
        public string in_quantity { get; set; }
        public string in_status { get; set; }
    }
}
