//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Inv_Update = new HashSet<Inv_Update>();
            this.Requests = new HashSet<Request>();
        }
    
        public string formType { get; set; }
        public string in_code { get; set; }
        public string in_name { get; set; }
        public string in_category { get; set; }
        public string in_type { get; set; }
        public string in_size { get; set; }
        public string in_quantity { get; set; }
        public string in_status { get; set; }
        public string in_class { get; set; }
        public string in_dateAdded { get; set; }
        public Nullable<System.DateTime> in_arch_date { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_Update> Inv_Update { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        public string FormattedDate
        {
            get { return in_arch_date?.ToString("MMMM dd, yyyy"); }
        }
    }
}
