//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewProject()
        {
            this.ReportImages = new HashSet<ReportImage>();
            this.NewManpowers = new HashSet<NewManpower>();
            this.NewReports = new HashSet<NewReport>();
        }
    
        public Nullable<System.Guid> proj_id { get; set; }
        public Nullable<int> proj_emp_no { get; set; }
        public int proj_type_id { get; set; }
        public string proj_name { get; set; }
        public string proj_subject { get; set; }
        public string proj_client { get; set; }
        public string proj_location { get; set; }
        public string proj_lead { get; set; }
        public string proj_status { get; set; }
        public Nullable<System.DateTime> proj_strDate { get; set; }
        public Nullable<System.DateTime> proj_endDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportImage> ReportImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewManpower> NewManpowers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewReport> NewReports { get; set; }
    }
}
