//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewProposal
    {
        public System.Guid prop_id { get; set; }
        public int prop_type_id { get; set; }
        public string prop_manpower { get; set; }
        public string prop_status { get; set; }
        public string prop_description { get; set; }
        public string prop_subject { get; set; }
        public Nullable<int> prop_emp_no { get; set; }
    
        public virtual NewProject NewProject { get; set; }
    }
}
