//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewReport()
        {
            this.ReportImages = new HashSet<ReportImage>();
        }
    
        public System.Guid rep_id { get; set; }
        public int rep_no { get; set; }
        public int rep_proj_id { get; set; }
        public string rep_scope { get; set; }
        public string rep_stats { get; set; }
        public System.DateTime rep_date { get; set; }
        public string rep_img { get; set; }
        public int rep_emp_no { get; set; }
        public string rep_description { get; set; }
    
        public virtual NewProject NewProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportImage> ReportImages { get; set; }
    }
}
