//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid guid { get; set; }
        public int emp_no { get; set; }
        public string in_code { get; set; }
        public string ntf_title { get; set; }
        public string ntf_content { get; set; }
        public System.DateTime ntf_date { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
