//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public System.Guid proj_id { get; set; }
        public int proj_emp_no { get; set; }
        public Nullable<int> proj_type_id { get; set; }
        public string proj_name { get; set; }
        public string proj_subject { get; set; }
        public string proj_client { get; set; }
        public string proj_location { get; set; }
        public string proj_lead { get; set; }
        public string proj_status { get; set; }
        public Nullable<System.DateTime> proj_strDate { get; set; }
        public Nullable<System.DateTime> proj_endDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
