//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportImage
    {
        public System.Guid img_id { get; set; }
        public Nullable<int> img_proj_id { get; set; }
        public string img_image { get; set; }
        public Nullable<System.DateTime> img_date { get; set; }
        public Nullable<int> img_rep_no { get; set; }
    
        public virtual NewProject NewProject { get; set; }
        public virtual NewReport NewReport { get; set; }
    }
}
