//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int emp_no { get; set; }
        public int role1 { get; set; }
        public string status { get; set; }
        public string date { get; set; }
        public string user_role {
            get
            {
                switch (role1)
                {
                    case 1:
                        return "admin";
                    case 2:
                        return "warehouse";
                    case 3:
                        return "office";
                }
                return "";
            }
        }

        public virtual Employee Employee { get; set; }
    }
}
