//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalFireSafety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtask
    {
        public System.Guid guid { get; set; }
        public System.Guid task_id { get; set; }
        public string subtask_name { get; set; }
        public int isDone { get; set; }
    
        public virtual TaskList TaskList { get; set; }
    }
}
